/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.jms.TextMessage;
import model.Client;

/**
 *
 * @author RafayMuneeb
 */
public class TopicsViewer extends javax.swing.JFrame implements Runnable {

	public static Client client = null;
    /**
     * Creates new form TopicsViewer
     *
     * @param username
     */
    public TopicsViewer(String username) {
        initComponents();
        Username = username;
        jLabel_Username.setText(username);

        client = new Client(username);
        System.out.println("trying to connect");
        client.connect();
        
        
        Thread receivingThread = new Thread(this);
        receivingThread.start();
    }
    public TopicsViewer(Client clt) {
        initComponents();
        
        client = clt;
        Username = client.getClientId();
        jLabel_Username.setText(Username);

        System.out.println("trying to connect");
        client.connect();
        
        
        Thread receivingThread = new Thread(this);
        receivingThread.start();
    }

    public TopicsViewer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        topicField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        blogField = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        tagsField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        feeds = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        postBlog = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        searchUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        followButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        followingList = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        jLabel_Username = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Blogger");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Topic:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Message:");

        blogField.setColumns(20);
        blogField.setRows(5);
        jScrollPane1.setViewportView(blogField);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Tags:");

        jScrollPane2.setViewportView(feeds);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Feeds");

        postBlog.setText("Post");
        postBlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postBlogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(topicField, 334, 334, 334)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel3)
        					.addGap(0, 273, Short.MAX_VALUE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabel4, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
        						.addComponent(tagsField, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addComponent(postBlog, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 370, GroupLayout.PREFERRED_SIZE))
        			.addGap(21))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(134)
        					.addComponent(jLabel5)))
        			.addContainerGap(747, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(jLabel2)
        			.addGap(1)
        			.addComponent(topicField, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel4)
        			.addGap(1)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(tagsField, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        				.addComponent(postBlog))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel5)
        			.addGap(14)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("User/Tag");

        followButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        followButton.setText("Follow");
        followButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followButtonActionPerformed(evt);
            }
        });

        followingList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(followingList);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Following:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel7)
        						.addComponent(jLabel8))
        					.addGap(18)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(searchUser, 220, 220, 220)
        						.addComponent(followButton, GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
        				.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel7)
        				.addComponent(searchUser, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
        			.addGap(23)
        			.addComponent(followButton, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel8)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel2.setLayout(jPanel2Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(241)
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 395, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(filler1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(257))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel_Username, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(783, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        					.addGap(25))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel_Username, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(109)
        					.addComponent(filler1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        					.addComponent(jPanel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        					.addComponent(jPanel2, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(26, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        


    private void followButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String searchtopicorusername = searchUser.getText();
        client.consumer.subscribe(searchtopicorusername);
        
        followingListArray.add(searchtopicorusername);
        String[] stringsL = new String[followingListArray.size()];
        stringsL = followingListArray.toArray(stringsL);
        final String[] strings2 = stringsL;

        followingList.setModel(new javax.swing.AbstractListModel() {
            @Override
            public boolean equals(Object o) {
                return super.equals(o); //To change body of generated methods, choose Tools | Templates.
            }

            public int getSize() {
                return strings2.length;
            }

            public Object getElementAt(int i) {
                return strings2[i];
            }
        });
        
    }                                            

    private void postBlogActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if (topicField.getText().equals("") || blogField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Title and Body are mandatory.");
        } else {
        	String msgBody = "msg";
        	String topic = "topic";
        	String tags = "tags";
        	
        	msgBody = blogField.getText();
        	topic = topicField.getText();
        	tags = tagsField.getText();
        	
        	TextMessage msg =  client.createTextMessage("Message from: "+Username);
            topic = topicField.getText();
            
            client.publisher.publish(msg);         
            client.publisher.createTopic(topic);
            client.consumer.subscribe(topic);
            client.publisher.publishToTopic(topic, msg);
            
            String blogPostValues = "Topic:" + topic + ", Details: " + msgBody + ", Tags: " + tags;

            blogPostArray.add(blogPostValues);
            String[] stringsL = new String[blogPostArray.size()];
            stringsL = blogPostArray.toArray(stringsL);
            final String[] strings2 = stringsL;

            feeds.setModel(new javax.swing.AbstractListModel() {
                public int getSize() {
                    return strings2.length;
                }

                public Object getElementAt(int i) {
                    return strings2[i];
                }
            });
            
        	
        }
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JTextArea blogField;
    private javax.swing.JList feeds;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton followButton;
    private javax.swing.JList followingList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton postBlog;
    private javax.swing.JTextField searchUser;
    private javax.swing.JTextField tagsField;
    private javax.swing.JTextField topicField;
    // End of variables declaration                   
    public ArrayList<String> followingListArray = new ArrayList<String>();
    public ArrayList<String> blogPostArray = new ArrayList<String>();
    public String Username = new String();

    public Thread receivingThread;

    private void insertInFeeds(String title,String msgbody,String tags) {

        String blogPostValues = "Topic:" + title+ ",Details: " + msgbody + ", Tags: " + tags;

        blogPostArray.add(blogPostValues);
        String[] stringsL = new String[blogPostArray.size()];
        stringsL = blogPostArray.toArray(stringsL);
        final String[] strings2 = stringsL;

        feeds.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                return strings2.length;
            }

            public Object getElementAt(int i) {
                return strings2[i];
            }
        });
    }

    
    @Override
    public void run() {
    	
    	String [] followedclients = client.consumer.getFollowedClients();
    	String [] followedtopics = client.consumer.getFollowedTopics();
    	
    	
    	
    	
    	receivingThread = new Thread(this);
        receivingThread.start();
        
    }

    

}
